const promessasBiblicas = [
  "Jeremias 29:11 - 'Pois eu bem sei os planos que estou projetando para vós, diz o Senhor; planos de paz, e não de mal, para vos dar um futuro e uma esperança.'",
  "Filipenses 4:19 - 'Meu Deus suprirá todas as vossas necessidades segundo as suas riquezas na glória em Cristo Jesus.'",
  "Isaías 41:10 - 'Não temas, porque eu sou contigo; não te assombres, porque eu sou teu Deus; eu te fortaleço, e te ajudo, e te sustento com a destra da minha justiça.'",
  "Romanos 8:28 - 'E sabemos que todas as coisas concorrem para o bem daqueles que amam a Deus, daqueles que são chamados segundo o seu propósito.'",
  "João 3:16 - 'Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.'",
  "Salmo 37:4 - 'Deleita-te também no Senhor, e ele te concederá o que deseja o teu coração.'",
  "Isaías 43:2 - 'Quando passares pelas águas, eu serei contigo; quando pelos rios, eles não te submergirão; quando passares pelo fogo, não te queimarás, nem a chama arderá em ti.'",
  "Josué 23:14 - 'Eis que vou hoje pelo caminho de toda a terra; e vós sabeis em vossos corações e em vossas almas que não tem falhado uma só palavra de todas as boas coisas que a vosso respeito falou o Senhor vosso Deus; nenhuma delas falhou, mas todas se cumpriram.'",
  "Salmo 91:10 - 'Nenhum mal te sucederá, nem praga alguma chegará à tua tenda.'",
  "Tiago 1:5 - 'Se algum de vocês tem falta de sabedoria, peça-a a Deus, que a todos dá livremente, de boa vontade; e lhe será concedida.'",
  "2 Coríntios 1:20 - 'Pois quantas forem as promessas feitas por Deus, tantas têm em Cristo o 'sim'. Por isso, por meio dele, o 'Amém' é pronunciado por nós para a glória de Deus.'",
  "Apocalipse 21:4 - 'Ele enxugará dos seus olhos toda lágrima. Não haverá mais morte, nem tristeza, nem choro, nem dor, pois a antiga ordem já passou.'",
  "Ezequiel 36:26 - 'Darei a vocês um coração novo e porei um espírito novo em vocês; tirarei de vocês o coração de pedra e, em troca, darei um coração de carne.'",
  "Isaías 26:3 - 'Tu, Senhor, guardarás em perfeita paz aquele cujo propósito está firme, porque em ti confia.'",
  "Lucas 18:27 - 'Jesus respondeu: 'O que é impossível para os homens é possível para Deus.''",
  "Salmo 34:4 - 'Busquei o Senhor, e ele me respondeu; livrou-me de todos os meus temores.'",
  "Salmo 84:11 - 'O Senhor Deus é sol e escudo; o Senhor concede favor e honra; não recusa nenhum bem aos que vivem com integridade.'",
  "João 5:28-29 - 'Não fiquem admirados com isto, pois está chegando a hora em que todos os que estiverem nos túmulos ouvirão a sua voz e sairão; os que fizeram o bem ressuscitarão para a vida, e os que fizeram o mal ressuscitarão para serem condenados.'",
  "Josué 1:9 - 'Não to mandei eu? Esforça-te, e tem bom ânimo; não temas, nem te espantes; porque o Senhor teu Deus é contigo, por onde quer que andares.'",
  "Mateus 11:28 - 'Vinde a mim, todos os que estais cansados e oprimidos, e eu vos aliviarei.'",
  "Salmo 23:1 - 'O Senhor é o meu pastor; nada me faltará.'",
  "Isaías 40:31 - 'Mas os que esperam no Senhor renovarão as suas forças; subirão com asas como águias; correrão, e não se cansarão; caminharão, e não se fatigarão.'",
  "Romanos 10:9 - 'Se com a tua boca confessares ao Senhor Jesus, e em teu coração creres que Deus o ressuscitou dos mortos, serás salvo.'",
  "Salmo 46:1 - 'Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.'",
  "Provérbios 3:5-6 - 'Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento. Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas.'",
  "Jeremias 33:3 - 'Clama a mim, e responder-te-ei, e anunciar-te-ei coisas grandes e firmes, que não sabes.'",
  "Salmo 55:22 - 'Lança o teu cuidado sobre o Senhor, e ele te susterá; nunca permitirá que o justo seja abalado.'",
  "Isaías 54:17 - 'Toda ferramenta preparada contra ti não prosperará; e toda língua que se levantar contra ti em juízo, tu a condenarás; esta é a herança dos servos do Senhor, e a sua justiça que de mim procede, diz o Senhor.'",
  "Romanos 8:38-39 - 'Porque estou certo de que, nem a morte, nem a vida, nem os anjos, nem os principados, nem as potestades, nem o presente, nem o porvir, nem a altura, nem a profundidade, nem alguma outra criatura nos poderá separar do amor de Deus, que está em Cristo Jesus nosso Senhor.'",
  "Salmo 121:7-8 - 'O Senhor te guardará de todo mal; ele guardará a tua alma. O Senhor guardará a tua entrada e a tua saída, desde agora e para sempre.'",
  "João 14:27 - 'Deixo-vos a paz, a minha paz vos dou; não vo-la dou como o mundo a dá. Não se turbe o vosso coração, nem se atemorize.'",
  "Hebreus 13:5 - 'Sejam vossos costumes sem avareza, contentando-vos com o que tendes; porque ele disse: Não te deixarei, nem te desampararei.'",
  "Salmo 91:11 - 'Porque aos seus anjos dará ordem a teu respeito, para te guardarem em todos os teus caminhos.'",
  "Mateus 6:33 - 'Mas buscai primeiro o reino de Deus, e a sua justiça, e todas estas coisas vos serão acrescentadas.'",
  "1 João 1:9 - 'Se confessarmos os nossos pecados, ele é fiel e justo para nos perdoar os pecados, e nos purificar de toda a injustiça.'",
  "Salmo 27:1 - 'O Senhor é a minha luz e a minha salvação; a quem temerei? O Senhor é a força da minha vida; de quem me recearei?'",
  "Isaías 41:13 - 'Porque eu, o Senhor teu Deus, te tomo pela tua mão direita; e te digo: Não temas, eu te ajudo.'",
  "Romanos 8:1 - 'Portanto, agora nenhuma condenação há para os que estão em Cristo Jesus, que não andam segundo a carne, mas segundo o Espírito.'",
  "Salmo 34:7 - 'O anjo do Senhor acampa-se ao redor dos que o temem, e os livra.'",
  "João 16:33 - 'Tenho-vos dito isto, para que em mim tenhais paz; no mundo tereis aflições, mas tende bom ânimo, eu venci o mundo.'",
  "Salmo 91:4 - 'Ele te cobrirá com as suas penas, e debaixo das suas asas te confiarás; a sua verdade será o teu escudo e broquel.'",
  "Isaías 40:29 - 'Dá força ao cansado, e multiplica as forças ao que não tem nenhum vigor.'",
  "Salmo 103:2-3 - 'Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum de seus benefícios. É ele que perdoa todas as tuas iniquidades, e sara todas as tuas enfermidades.'",
  "João 14:1 - 'Não se turbe o vosso coração; credes em Deus, crede também em mim.'",
  "Salmo 91:15 - 'Ele me invocará, e eu lhe responderei; estarei com ele na angústia; dela o retirarei, e o glorificarei.'",
]

export default promessasBiblicas
